import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';
import 'models/character.dart';
import 'models/game_state.dart';
import 'models/combat_log.dart';
import 'models/equipment.dart';
import 'models/skill_tree.dart';
import 'models/bestiary.dart';
import 'models/companion.dart';
import 'models/guild_hall.dart';
import 'models/enchanting.dart';
import 'models/boss_rush.dart';
import 'models/professions.dart';
import 'models/equipment_sets.dart';
import 'models/transmutation.dart';
import 'models/alchemy.dart';
import 'models/legendary_items.dart';
import 'models/infinite_spiral.dart';
import 'providers/game_provider.dart';
import 'services/time_manager.dart';
import 'screens/dashboard_screen.dart';
import 'screens/character_creation_screen.dart';
import 'config/configuration_manager.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load configuration first
  await ConfigurationManager.initialize();

  await Hive.initFlutter();

  Hive.registerAdapter(CharacterAdapter());
  Hive.registerAdapter(GameStateAdapter());
  Hive.registerAdapter(CombatLogAdapter());
  Hive.registerAdapter(EquipmentAdapter());
  Hive.registerAdapter(InventoryAdapter());
  Hive.registerAdapter(SkillTreeAdapter());
  Hive.registerAdapter(BestiaryAdapter());
  Hive.registerAdapter(CompanionAdapter());
  Hive.registerAdapter(CompanionRosterAdapter());
  Hive.registerAdapter(RoomAdapter());
  Hive.registerAdapter(EchoNPCAdapter());
  Hive.registerAdapter(GuildHallAdapter());

  // Enchanting adapters
  Hive.registerAdapter(GemTypeAdapter());
  Hive.registerAdapter(GemTierAdapter());
  Hive.registerAdapter(PrefixTypeAdapter());
  Hive.registerAdapter(SuffixTypeAdapter());
  Hive.registerAdapter(CurseTypeAdapter());
  Hive.registerAdapter(GemAdapter());
  Hive.registerAdapter(EnchantmentAdapter());
  Hive.registerAdapter(SocketAdapter());
  Hive.registerAdapter(EnchantedEquipmentAdapter());

  // Boss Rush adapters
  Hive.registerAdapter(BossMechanicAdapter());
  Hive.registerAdapter(EssenceTypeAdapter());
  Hive.registerAdapter(RiftModifierAdapter());
  Hive.registerAdapter(BossAdapter());
  Hive.registerAdapter(EchoEntryAdapter());
  Hive.registerAdapter(RiftAdapter());
  Hive.registerAdapter(BossRushStateAdapter());

  // Profession adapters
  Hive.registerAdapter(ProfessionTypeAdapter());
  Hive.registerAdapter(MaterialTypeAdapter());
  Hive.registerAdapter(CraftedItemTypeAdapter());
  Hive.registerAdapter(MaterialAdapter());
  Hive.registerAdapter(CraftingRecipeAdapter());
  Hive.registerAdapter(ProfessionAdapter());
  Hive.registerAdapter(ProfessionStateAdapter());

  // Equipment Set adapters
  Hive.registerAdapter(SetNameAdapter());
  Hive.registerAdapter(SetBonusTypeAdapter());
  Hive.registerAdapter(SetBonusAdapter());
  Hive.registerAdapter(EquipmentSetAdapter());
  Hive.registerAdapter(ActiveSetAdapter());
  Hive.registerAdapter(SetSynergyAdapter());
  Hive.registerAdapter(EquipmentSetStateAdapter());
  Hive.registerAdapter(EquipmentSetItemAdapter());

  // Transmutation adapters (generated by build_runner)
  // TODO: Uncomment after running flutter pub run build_runner build
  // Hive.registerAdapter(ItemTierAdapter());
  // Hive.registerAdapter(TransmutableItemTypeAdapter());
  // Hive.registerAdapter(VolatileResultAdapter());
  // Hive.registerAdapter(TransmutationRecipeAdapter());
  // Hive.registerAdapter(TransmutationResultAdapter());
  // Hive.registerAdapter(TransmutationHistoryAdapter());
  // Hive.registerAdapter(TransmutationStateAdapter());

  // Alchemy adapters (generated by build_runner)
  // TODO: Uncomment after running flutter pub run build_runner build
  // Hive.registerAdapter(PotionTypeAdapter());
  // Hive.registerAdapter(PotionEffectAdapter());
  // Hive.registerAdapter(AlchemyRecipeAdapter());
  // Hive.registerAdapter(BrewingSlotAdapter());
  // Hive.registerAdapter(AlchemyStateAdapter());

  // Legendary Items adapters (generated by build_runner)
  // TODO: Uncomment after running flutter pub run build_runner build
  // Hive.registerAdapter(LegendaryEffectTypeAdapter());
  // Hive.registerAdapter(SentienceTypeAdapter());
  // Hive.registerAdapter(EquipmentSlotTypeAdapter());
  // Hive.registerAdapter(StatBonusAdapter());
  // Hive.registerAdapter(LegendaryEffectAdapter());
  // Hive.registerAdapter(LegendaryItemAdapter());
  // Hive.registerAdapter(LegendaryCollectionAdapter());

  // Infinite Spiral adapters (generated by build_runner)
  // TODO: Uncomment after running flutter pub run build_runner build
  // Hive.registerAdapter(SpiralStateAdapter());
  // Hive.registerAdapter(SpiralLoopAdapter());
  // Hive.registerAdapter(TaleTypeAdapter());
  // Hive.registerAdapter(TaleBonusAdapter());
  // Hive.registerAdapter(TaleAdapter());
  // Hive.registerAdapter(TalesCollectionAdapter());
  // Hive.registerAdapter(InfiniteSpiralAdapter());

  final characterBox = await Hive.openBox<Character>('character');
  final gameStateBox = await Hive.openBox<GameState>('gameState');
  final combatLogBox = await Hive.openBox<CombatLog>('combatLog');
  final skillTreeBox = await Hive.openBox<SkillTree>('skillTree');
  final bestiaryBox = await Hive.openBox<Bestiary>('bestiary');
  final companionBox = await Hive.openBox<CompanionRoster>('companions');
  final guildHallBox = await Hive.openBox<GuildHall>('guildHall');
  final bossRushBox = await Hive.openBox<BossRushState>('bossRush');
  final professionBox = await Hive.openBox<ProfessionState>('professions');
  final equipmentSetBox = await Hive.openBox<EquipmentSetState>(
    'equipmentSets',
  );
  final transmutationBox = await Hive.openBox<TransmutationState>(
    'transmutation',
  );
  final alchemyBox = await Hive.openBox<AlchemyState>('alchemy');
  final legendaryBox = await Hive.openBox<LegendaryCollection>('legendary');
  final spiralBox = await Hive.openBox<InfiniteSpiral>('spiral');

  final timeManager = TimeManager();

  // Check if we have existing character data
  final hasExistingCharacter = characterBox.get('main') != null;

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (_) => GameProvider(
            characterBox,
            gameStateBox,
            combatLogBox,
            skillTreeBox,
            bestiaryBox,
            companionBox,
            guildHallBox,
            bossRushBox,
            professionBox,
            equipmentSetBox,
            transmutationBox,
            alchemyBox,
            legendaryBox,
            spiralBox,
            timeManager,
          ),
        ),
      ],
      child: MainApp(hasExistingCharacter: hasExistingCharacter),
    ),
  );
}

class MainApp extends StatelessWidget {
  final bool hasExistingCharacter;

  const MainApp({super.key, required this.hasExistingCharacter});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: ConfigurationManager.appName,
      debugShowCheckedModeBanner: ConfigurationManager.debugMode,
      theme: ThemeData.dark(useMaterial3: false).copyWith(
        scaffoldBackgroundColor: Colors.black,
        textTheme: ThemeData.dark().textTheme.apply(fontFamily: 'Courier New'),
      ),
      home: hasExistingCharacter
          ? const AppLifecycleWrapper()
          : CharacterCreationWrapper(),
    );
  }
}

/// Wrapper for character creation that handles the transition to main game
class CharacterCreationWrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CharacterCreationScreen(
      onCreate: (name, race, className, stats) {
        _createCharacterAndStart(context, name, race, className, stats);
      },
    );
  }

  void _createCharacterAndStart(
    BuildContext context,
    String name,
    String race,
    String className,
    Map<String, int> stats,
  ) {
    final gameProvider = context.read<GameProvider>();

    // Create the character with custom stats
    gameProvider.createCustomCharacter(
      name: name,
      race: race,
      characterClass: className,
      stats: stats,
    );

    // Navigate to main game
    Navigator.of(context).pushReplacement(
      MaterialPageRoute(builder: (context) => const AppLifecycleWrapper()),
    );
  }
}

class AppLifecycleWrapper extends StatefulWidget {
  const AppLifecycleWrapper({super.key});

  @override
  State<AppLifecycleWrapper> createState() => _AppLifecycleWrapperState();
}

class _AppLifecycleWrapperState extends State<AppLifecycleWrapper>
    with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    final gameProvider = context.read<GameProvider>();

    if (state == AppLifecycleState.paused ||
        state == AppLifecycleState.inactive) {
      gameProvider.onAppPause();
    } else if (state == AppLifecycleState.resumed) {
      gameProvider.onAppResume();
    }
  }

  @override
  Widget build(BuildContext context) {
    return const DashboardScreen();
  }
}
